const SERVER = {
  PORT: 'PORT',
  NODE_ENV: 'NODE_ENV',
  DOMAIN: 'DOMAIN'
} as const;

const OAUTH = {
  NAVER_CLIENT_ID: 'NAVER_CLIENT_ID',
  NAVER_CLIENT_SECRET: 'NAVER_CLIENT_SECRET',
  NAVER_REDIRECT_URI: 'NAVER_REDIRECT_URI',

  KAKAO_CLIENT_ID: 'KAKAO_CLIENT_ID',
  KAKAO_REDIRECT_URI: 'KAKAO_REDIRECT_URI',

  GOOGLE_CLIENT_ID: 'GOOGLE_CLIENT_ID',
  GOOGLE_CLIENT_SECRET: 'GOOGLE_CLIENT_SECRET',
  GOOGLE_REDIRECT_URI: 'GOOGLE_REDIRECT_URI'
} as const;

/**
 * 각 주제에 맞게 묶어서 export 하지 않는 변수로 생성하고
 * ENV_KEY 객체에 spread
 */
export const ENV_KEY = {
  ...SERVER,
  ...OAUTH
} as const;
