branchName: "/#${issue.number}/${issue.title[0,25]}"
gitSafeReplacementChar: "_"
defaultBranch: "develop"
autoCloseIssue: true
commentMessage: "Branch ${branchName} created for issue: ${issue.title}"
branches:
  - label: Setting
    prefix: setting
  - label: Feat
    prefix: feat
  - label: Deploy
    prefix: Deploy
  - label: BugFix
    prefix: bugfix
  - label: Doc
    prefix: doc
  - label: API
    prefix: api
  - label: Refactor
    prefix: refactor
  - label: Modify
    prefix: modify
  - label: Test
    prefix: test
