export const COMMON_ERROR_HTTP_STATUS_CODE = {
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  METHOD_NOT_ALLOWED: 405,
  CONFLICT: 409,
  INTERNAL_SERVER_ERROR: 500
} as const;

export const COMMON_ERROR_HTTP_STATUS_MESSAGE: Required<{
  [key in (typeof COMMON_ERROR_HTTP_STATUS_CODE)[keyof typeof COMMON_ERROR_HTTP_STATUS_CODE]]: string;
}> = {
  [COMMON_ERROR_HTTP_STATUS_CODE.BAD_REQUEST]: 'Bad Request',
  [COMMON_ERROR_HTTP_STATUS_CODE.UNAUTHORIZED]: 'Unauthorized',
  [COMMON_ERROR_HTTP_STATUS_CODE.FORBIDDEN]: 'Forbidden',
  [COMMON_ERROR_HTTP_STATUS_CODE.NOT_FOUND]: 'Not found',
  [COMMON_ERROR_HTTP_STATUS_CODE.METHOD_NOT_ALLOWED]: 'Method not allowed',
  [COMMON_ERROR_HTTP_STATUS_CODE.CONFLICT]: 'Conflict',
  [COMMON_ERROR_HTTP_STATUS_CODE.INTERNAL_SERVER_ERROR]: 'Internal server error'
} as const;
