name: Develop CI

on:
  push:
    branches: ["develop"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login Dockerhub
        env:
          DOCKER_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKERHUB_PASSWORD}}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Build Docker Image
        run: docker build -t ${{secrets.DOCKER_DEVELOP_IMAGE_NAME}}:latest .

      - name: Push Docker Image
        run: docker push ${{secrets.DOCKER_DEVELOP_IMAGE_NAME}}:latest