name: Build on PR
on:
  push:
    branches-ignore:
      - main
      - develop
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.14.0

      - name: Install Dependencies
        run: npm ci

      - name: Lint
        run: npm run lint
